# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import proyecto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('legajo', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('externo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Orientacion - Rama',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_inscripcion', models.DateField()),
                ('fecha_anteproyecto', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('anteproyecto', models.FileField(blank=True, null=True, upload_to=proyecto.models.pdf_path_and_rename)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('alumnos', models.ManyToManyField(to='proyecto.Alumno')),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asesor', to='proyecto.Director')),
                ('co_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_director', to='proyecto.Director')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.Director')),
                ('orientacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.Orientacion')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Plan')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='orientacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Orientacion'),
        ),
    ]
