# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20190402_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='orientacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proyecto.Orientacion'),
        ),
    ]
