# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20190402_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='director',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='proyecto.Director'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='orientacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='proyecto.Orientacion'),
            preserve_default=False,
        ),
    ]
